- hosts: all
  serial: 1
  tasks:
    - name: get iDRAC info
      community.general.idrac_redfish_info:
        baseuri: "{{idrac_host}}"
        username: "{{idrac_user}}"
        password: "{{idrac_password}}"
        category: Manager
        command: GetManagerAttributes
      delegate_to: localhost
      register: idrac_info

    - name: get firmware inventory
      dellemc.openmanage.idrac_firmware_info:
        idrac_ip: "{{idrac_host}}"
        idrac_user: "{{idrac_user}}"
        idrac_password: "{{idrac_password}}"
      delegate_to: localhost
      register: idrac_firmware

    - name: store firmware facts
      set_fact:
        current_idrac_version: "{{ (idrac_info.redfish_facts.entries | selectattr('Id', 'defined') | selectattr('Id', 'equalto', 'iDRACAttributes') | list | first)['Attributes']['Info.1.Version'] }}"
        current_bios_version: "{{ (idrac_firmware.firmware_info.Firmware | selectattr('ComponentType', 'defined') | selectattr('ComponentType', 'equalto', 'BIOS') | list | first)['VersionString'] }}"
        current_cpld_version: "{{ (idrac_firmware.firmware_info.Firmware | selectattr('FQDD', 'defined') | selectattr('FQDD', 'equalto', 'CPLD.Embedded.1') | list | first)['VersionString'] }}"

    - name: Drain node
      tags: [ kubectl ]
      delegate_to: "{{ (rke2_role == 'agent') | ternary ('eaglei-vmhost04.ornl.gov', inventory_hostname) }}"
      command: "/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml drain {{inventory_hostname}} --force --ignore-daemonsets --delete-emptydir-data"

    - name: Update packages
      yum:
        name: "*"
        state: latest
      register: yum_updates

    - name: Temporarily disable PCR checking
      register: clevis_disable_pcr
      when: >
        false and (
        yum_updates.changed or
        ( desired_bios_version != current_bios_version ) or
        ( desired_cpld_version != current_clpd_version ) )
      command: >
        clevis luks edit -d /dev/sdb4 -s 1 -c
        '{"hash": "sha256", "key": "ecc"}'

    - reboot: {}
      when: "yum_updates.changed"

    - when: "desired_bios_version != current_bios_version"
      block:
      - name: Upgrade BIOS
        dellemc.openmanage.redfish_firmware:
          baseuri: "{{idrac_host}}"
          username: "{{idrac_user}}"
          password: "{{idrac_password}}"
          image_uri: "./updates/BIOS_{{desired_bios_version}}.EXE"
        delegate_to: localhost
      - name: Reboot post-BIOS upgrade
        reboot:
          reboot_timeout: 1800

    - when: "desired_cpld_version != current_cpld_version"
      block:
      - name: Upgrade CPLD
        dellemc.openmanage.redfish_firmware:
          baseuri: "{{idrac_host}}"
          username: "{{idrac_user}}"
          password: "{{idrac_password}}"
          image_uri: "./updates/CPLD_{{desired_clpd_version}}.EXE"
        delegate_to: localhost
      - name: Reboot post-CPLD upgrade
        reboot:
          reboot_timeout: 1800

    - when: "desired_idrac_version != current_idrac_version"
      block:
      - name: Upgrade iDRAC
        dellemc.openmanage.redfish_firmware:
          baseuri: "{{idrac_host}}"
          username: "{{idrac_user}}"
          password: "{{idrac_password}}"
          image_uri: "./updates/iDRAC_{{desired_idrac_version}}.EXE"
        delegate_to: localhost
      - name: Waiting for iDRAC to go down for upgrade
        wait_for:
          port: 22
          host: "{{idrac_host}}"
          state: stopped
          timeout: 600
        delegate_to: localhost
      - name: Waiting for iDRAC to come back after upgrade
        wait_for:
          port: 22
          host: "{{idrac_host}}"
          state: started
          timeout: 600
        delegate_to: localhost

    - name: Resume PCR checking
      when: no
      #when: not clevis_disable_pcr.skipped
      command: >
        clevis luks edit -d /dev/sdb4 -s 1 -c
        '{"hash": "sha256", "key": "ecc","pcr_bank": "sha1", "pcr_ids": "0,2,4,6,7,8,9"}'

    - name: "Wait for kubectl to be responsive"
      tags: [ kubectl ]
      when: 'rke2_role == "server"'
      command: "/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml version"
      register: wait_kubectl_ready
      changed_when: False
      until: wait_kubectl_ready.rc == 0
      retries: 20
      delay: 5

    - name: "Uncordon node"
      tags: [ kubectl, uncordontest ]
      delegate_to: "{{ (rke2_role == 'agent') | ternary ('eaglei-vmhost04.ornl.gov', inventory_hostname) }}"
      command: "/var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml uncordon {{inventory_hostname}}"

    - name: "Pause to allow rescheduling"
      tags: [ kubectl ]
      pause:
        minutes: 2
